services:
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./laravel:/app
    command: composer install --ignore-platform-reqs
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=weather_db
      - MYSQL_USER=weather_user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    expose:
      - '3306'
  myapp:
    image: docker.io/bitnami/laravel:10
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=weather_user
      - DB_PASSWORD=pass
      - DB_DATABASE=weather_db
    volumes:
      - './laravel:/app'
    depends_on:
      mysql:
        condition: service_started
      composer_installation:
        condition: service_completed_successfully